server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/campus_society?useSSL=false&serverTimezone=UTC&characterEncoding=utf8}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    open-in-view: false

logging:
  level:
    com.social.csocial: INFO
    org.hibernate.SQL: WARN



springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
